### ISSUE TITLE
Propose to add "Connected Papers"

### ISSUE THREAD

**Issue by phrasenmaeher** [emptymalei/awesome-research#52]
[Connected Papers](https://www.connectedpapers.com) is a web application that lets researchers find interesting/relevant/most cited papers beginning with an initial starter paper. This tool is useful if you dive into a novel topic and want to get an overview. Further, it can point you to other crucial papers.

**Comment by emptymalei** [comment]
Hi @phrasenmaeher , thanks for the proposal. This repo is not being actively maintained anymore. Instead, we have a website and connectedpapers is already part of it: 
https://tools.kausalflow.com/tools/connectedpapers/

If you would like to have connectedpapers in this repo, feel free to create a PR. Otherwise, I recommend checking out [the website](https://tools.kausalflow.com/).

**Comment by phrasenmaeher** [comment]
This answers my question, thanks!
